name: Publish to Cloudflare Pages

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Cloudflare Pages
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Build with MkDocs
        run: mkdocs build
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: 'it-virtuoso-kb' # !!! CHANGE THIS TO YOUR CLOUDFLARE PAGES PROJECT NAME !!!
          directory: 'site'
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
